hidden_size: 64 #The number of features in the hidden state. It is also the initial embedding size of items. Defaults to 64.

inner_size: 256 #The inner hidden size in feed-forward layer. Defaults to 256.

n_layers: 2 #The number of transformer layers in transformer encoder. Defaults to 2.

n_heads: 2 #The number of attention heads for multi-head attention layer. Defaults to 2.

hidden_dropout_prob: 0.5 #The probability of an element to be zeroed. Defaults to 0.5.

attn_dropout_prob: 0.5 #The probability of an attention score to be zeroed. Defaults to 0.5.

mask_ratio: 0.2 #The probability for a item replaced by MASK token. Defaults to 0.2.
